"""
app/reporting/investment_report.py
-----------------------------------
Pipeline Step 5: LLM-generated Investment Memo

Inputs:  ValuationResult + DVFComparables + listing metadata
Outputs: Structured investment memo with:
  - Executive summary (1-2 sentences)
  - Valuation analysis
  - Market context
  - Risk factors
  - Investment recommendation

Design decisions:
  - Structured prompt with explicit output format (not free-form)
  - All factual claims grounded in DVF data (no hallucination risk on numbers)
  - LLM role is NARRATIVE, not CALCULATION
    → calculations done in Python, LLM only generates prose around them
  - Confidence score shown explicitly in report
    → reader knows "15 comparables, 45 days fresh" vs "3 comparables, 8 months old"
  - Fallback: template-based report if LLM unavailable

Interview-ready explanation:
  "The LLM doesn't do the math. It translates pre-computed numbers
   into human-readable investment rationale. This prevents hallucination
   on financial figures and keeps the pipeline auditable."
"""

import logging
from dataclasses import dataclass
from typing import Optional
import json

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Report schema
# ---------------------------------------------------------------------------

@dataclass
class InvestmentReport:
    listing_id: str
    executive_summary: str
    valuation_section: str
    market_context: str
    risk_factors: str
    recommendation: str
    data_note: str
    generated_by: str          # "llm" | "template"

    def to_text(self) -> str:
        return f"""
INVESTMENT MEMO — {self.listing_id}
{'='*50}

EXECUTIVE SUMMARY
{self.executive_summary}

VALUATION ANALYSIS
{self.valuation_section}

MARKET CONTEXT
{self.market_context}

RISK FACTORS
{self.risk_factors}

RECOMMENDATION
{self.recommendation}

DATA NOTE
{self.data_note}

[Generated by: {self.generated_by}]
""".strip()

    def to_dict(self) -> dict:
        return {
            "listing_id": self.listing_id,
            "executive_summary": self.executive_summary,
            "valuation": self.valuation_section,
            "market_context": self.market_context,
            "risk_factors": self.risk_factors,
            "recommendation": self.recommendation,
            "data_note": self.data_note,
            "generated_by": self.generated_by,
        }


# ---------------------------------------------------------------------------
# Report generator
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are a senior real estate investment analyst at a Paris-based crowdfunding platform.
Write concise, professional investment memos in English.
Base your analysis strictly on the data provided — never invent figures.
Be direct about uncertainty when data confidence is low.
Tone: institutional, factual, no marketing language."""

REPORT_PROMPT_TEMPLATE = """
Generate an investment memo for the following property. Use ONLY the provided data.

PROPERTY DATA:
- Listing ID: {listing_id}
- Address: {address}
- Type: {property_type} | Surface: {surface_m2}m² | Zipcode: {zipcode}

VALUATION:
- Asking price: {asking_price:,}€ ({asking_m2:.0f} €/m²)
- Fair value estimate: {fair_value:,}€ ({fair_m2:.0f} €/m²)
- 80% Confidence interval: {ci_low:,}€ — {ci_high:,}€
- Price gap: {price_gap:+.1f}% vs fair value
- Signal: {signal} ({signal_strength})

DVF MARKET DATA:
- Comparable transactions: {n_comparables}
- Market median price/m²: {market_m2:.0f} €/m²
- Data freshness: {freshness:.0f} days
- YoY price trend: {trend:+.1f}%
- Data confidence score: {confidence:.2f}/1.00

Generate a structured memo with these exact sections:
1. EXECUTIVE SUMMARY (2 sentences max)
2. VALUATION ANALYSIS (explain the gap, CI, what it means)
3. MARKET CONTEXT (trend, comparable volume, neighbourhood)
4. RISK FACTORS (data quality, market risks, property-specific)
5. RECOMMENDATION (buy / monitor / pass — with condition)

Return ONLY valid JSON:
{{
  "executive_summary": "...",
  "valuation_section": "...",
  "market_context": "...",
  "risk_factors": "...",
  "recommendation": "..."
}}"""


class InvestmentReportGenerator:
    """
    Generates LLM investment memos, with template fallback.

    Key constraint: LLM generates prose only.
    All numbers in the prompt are pre-computed from DVF + model.
    """

    def __init__(self, llm_client=None):
        self.llm_client = llm_client

    def generate(
        self,
        valuation,          # ValuationResult
        comparables,        # DVFComparables
        listing_metadata: dict,
    ) -> InvestmentReport:

        if self.llm_client:
            try:
                return self._generate_llm(valuation, comparables, listing_metadata)
            except Exception as e:
                logger.warning(f"LLM report generation failed ({e}) — using template")

        return self._generate_template(valuation, comparables, listing_metadata)

    def _build_prompt(self, valuation, comparables, meta: dict) -> str:
        return REPORT_PROMPT_TEMPLATE.format(
            listing_id=valuation.listing_id,
            address=meta.get("address_clean", "Paris"),
            property_type=meta.get("property_type", "Appartement"),
            surface_m2=valuation.features_used.get("surface_m2", "N/A"),
            zipcode=valuation.features_used.get("zipcode", "75XXX"),
            asking_price=valuation.asking_price,
            asking_m2=valuation.asking_price / max(valuation.features_used.get("surface_m2", 1), 1),
            fair_value=valuation.predicted_fair_value,
            fair_m2=valuation.predicted_m2,
            ci_low=valuation.ci_low,
            ci_high=valuation.ci_high,
            price_gap=valuation.price_gap_pct,
            signal=valuation.signal,
            signal_strength=valuation.signal_strength,
            n_comparables=comparables.n_transactions,
            market_m2=comparables.market_median_m2,
            freshness=comparables.freshness_days,
            trend=comparables.market_trend_pct,
            confidence=valuation.confidence_score,
        )

    def _generate_llm(self, valuation, comparables, meta: dict) -> InvestmentReport:
        import re
        prompt = self._build_prompt(valuation, comparables, meta)

        response = self.llm_client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1000,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}]
        )

        raw = response.content[0].text.strip()
        raw = re.sub(r"```json|```", "", raw).strip()
        data = json.loads(raw)

        confidence_note = (
            f"Based on {comparables.n_transactions} DVF comparable transactions "
            f"(avg {comparables.freshness_days:.0f} days old). "
            f"Data confidence: {valuation.confidence_score:.2f}/1.00. "
            f"{'High confidence.' if valuation.confidence_score > 0.7 else 'Use with caution — limited data.'}"
        )

        return InvestmentReport(
            listing_id=valuation.listing_id,
            executive_summary=data["executive_summary"],
            valuation_section=data["valuation_section"],
            market_context=data["market_context"],
            risk_factors=data["risk_factors"],
            recommendation=data["recommendation"],
            data_note=confidence_note,
            generated_by="llm:claude-sonnet-4",
        )

    def _generate_template(self, valuation, comparables, meta: dict) -> InvestmentReport:
        """
        Deterministic template report when LLM unavailable.
        Used in CI, testing, demo mode.
        """
        surface = valuation.features_used.get("surface_m2", "N/A")
        zipcode = valuation.features_used.get("zipcode", "75XXX")

        gap_desc = (
            f"undervalued by {abs(valuation.price_gap_pct):.1f}%"
            if valuation.signal == "undervalued"
            else f"overvalued by {valuation.price_gap_pct:.1f}%"
            if valuation.signal == "overvalued"
            else "fairly priced"
        )

        exec_summary = (
            f"This {surface}m² property in Paris {zipcode} appears {gap_desc} "
            f"relative to recent DVF transactions. "
            f"{'Warrants further due diligence.' if valuation.signal != 'overvalued' else 'Caution advised.'}"
        )

        valuation_text = (
            f"Asking price: {valuation.asking_price:,}€. "
            f"Model estimate: {valuation.predicted_fair_value:,}€ "
            f"(80% CI: {valuation.ci_low:,}€ – {valuation.ci_high:,}€). "
            f"Gap: {valuation.price_gap_pct:+.1f}% vs fair value."
        )

        market_text = (
            f"Based on {comparables.n_transactions} comparable transactions in Paris {zipcode}. "
            f"Market median: {comparables.market_median_m2:,.0f} €/m². "
            f"YoY trend: {comparables.market_trend_pct:+.1f}%."
        )

        risk_text = (
            f"Data confidence: {valuation.confidence_score:.2f}/1.00 "
            f"({'adequate' if valuation.confidence_score > 0.6 else 'limited — verify independently'}). "
            f"Data freshness: {comparables.freshness_days:.0f} days. "
            "Macro risks: interest rate sensitivity, Paris rental regulation."
        )

        if valuation.signal == "undervalued" and valuation.confidence_score > 0.5:
            rec = f"MONITOR — Potential discount of {abs(valuation.price_gap_pct):.1f}%. Verify address and surface. Request diagnostics."
        elif valuation.signal == "overvalued":
            rec = f"PASS — Asking price exceeds fair value by {valuation.price_gap_pct:.1f}%. Negotiate or skip."
        else:
            rec = "NEUTRAL — Fairly priced. Decision depends on yield expectations and strategic fit."

        confidence_note = (
            f"Template report (LLM unavailable). "
            f"{comparables.n_transactions} DVF comparables, "
            f"{comparables.freshness_days:.0f}d avg age. "
            f"Confidence: {valuation.confidence_score:.2f}/1.00."
        )

        return InvestmentReport(
            listing_id=valuation.listing_id,
            executive_summary=exec_summary,
            valuation_section=valuation_text,
            market_context=market_text,
            risk_factors=risk_text,
            recommendation=rec,
            data_note=confidence_note,
            generated_by="template",
        )
